export const MEDIUM_CARDS_POSTS = [
  {
    id: 101,
    image: "https://cdn.mos.cms.futurecdn.net/FmpZJJVrUEuiqgQmMFHqkE-840-80.jpg.webp",
    date: "April 20, 2021",
    title: "Astronauts prep for new solar arrays on nearly seven-hour spacewalk",
    imageLike: '../../../public/like-2.svg',
    imageDislike: '../../../public/dislike-2.svg',
    imageSave: '../../../public/save-2.svg',
    imageDetails: '../../../public/details.svg',
  },
   {
    id: 102,
    image: "https://cdn.mos.cms.futurecdn.net/FmpZJJVrUEuiqgQmMFHqkE-840-80.jpg.webp",
    date: "April 20, 2021",
    title: "Astronauts prep for new solar arrays on nearly seven-hour spacewalk",
    imageLike: '../../../public/like-2.svg',
    imageDislike: '../../../public/dislike-2.svg',
    imageSave: '../../../public/save-2.svg',
    imageDetails: '../../../public/details.svg',
  },
    {
    id: 103,
    image: "https://cdn.mos.cms.futurecdn.net/FmpZJJVrUEuiqgQmMFHqkE-840-80.jpg.webp",
    date: "April 20, 2021",
    title: "Astronauts prep for new solar arrays on nearly seven-hour spacewalk",
    imageLike: '../../../public/like-2.svg',
    imageDislike: '../../../public/dislike-2.svg',
    imageSave: '../../../public/save-2.svg',
    imageDetails: '../../../public/details.svg',
    },
     {
    id: 104,
    image: "https://cdn.mos.cms.futurecdn.net/FmpZJJVrUEuiqgQmMFHqkE-840-80.jpg.webp",
    date: "April 20, 2021",
    title: "Astronauts prep for new solar arrays on nearly seven-hour spacewalk",
    imageLike: '../../../public/like-2.svg',
    imageDislike: '../../../public/dislike-2.svg',
    imageSave: '../../../public/save-2.svg',
    imageDetails: '../../../public/details.svg',
  },
]