export const SMALL_CARDS_POSTS = [
  {
    id: 201,
    image: "https://spaceflightnow.com/wp-content/uploads/2022/03/eva79-helmetcam.jpg",
    date: "April 20, 2021",
    title: "Astronauts prep for new solar arrays on nearly seven-hour spacewalk",
    imageLike: '../../../public/like-2.svg',
    imageDislike: '../../../public/dislike-2.svg',
    imageSave: '../../../public/save-2.svg',
    imageDetails: '../../../public/details.svg',
  },
  {
    id: 202,
    image: "https://spaceflightnow.com/wp-content/uploads/2022/03/eva79-helmetcam.jpg",
    date: "April 20, 2021",
    title: "Astronauts prep for new solar arrays on nearly seven-hour spacewalk",
    imageLike: '../../../public/like-2.svg',
    imageDislike: '../../../public/dislike-2.svg',
    imageSave: '../../../public/save-2.svg',
    imageDetails: '../../../public/details.svg',
  },
  {
    id: 203,
    image: "https://spaceflightnow.com/wp-content/uploads/2022/03/eva79-helmetcam.jpg",
    date: "April 20, 2021",
    title: "Astronauts prep for new solar arrays on nearly seven-hour spacewalk",
    imageLike: '../../../public/like-2.svg',
    imageDislike: '../../../public/dislike-2.svg',
    imageSave: '../../../public/save-2.svg',
    imageDetails: '../../../public/details.svg',
  },
  {
    id: 204,
    image: "https://spaceflightnow.com/wp-content/uploads/2022/03/eva79-helmetcam.jpg",
    date: "April 20, 2021",
    title: "Astronauts prep for new solar arrays on nearly seven-hour spacewalk",
    imageLike: '../../../public/like-2.svg',
    imageDislike: '../../../public/dislike-2.svg',
    imageSave: '../../../public/save-2.svg',
    imageDetails: '../../../public/details.svg',
  },
  {
    id: 205,
    image: "https://spaceflightnow.com/wp-content/uploads/2022/03/eva79-helmetcam.jpg",
    date: "April 20, 2021",
    title: "Astronauts prep for new solar arrays on nearly seven-hour spacewalk",
    imageLike: '../../../public/like-2.svg',
    imageDislike: '../../../public/dislike-2.svg',
    imageSave: '../../../public/save-2.svg',
    imageDetails: '../../../public/details.svg',
  },
  {
    id: 206,
    image: "https://spaceflightnow.com/wp-content/uploads/2022/03/eva79-helmetcam.jpg",
    date: "April 20, 2021",
    title: "Astronauts prep for new solar arrays on nearly seven-hour spacewalk",
    imageLike: '../../../public/like-2.svg',
    imageDislike: '../../../public/dislike-2.svg',
    imageSave: '../../../public/save-2.svg',
    imageDetails: '../../../public/details.svg',
  },
]