export const SMALL_CARDS_POSTS = [
  {
    id: 201,
    image: "https://spaceflightnow.com/wp-content/uploads/2022/03/eva79-helmetcam.jpg",
    date: "August 4, 2025",
    title: "The International Space Station NASA plans to extend logistics support",
    imageLike: '../../../public/like-2.svg',
    imageDislike: '../../../public/dislike-2.svg',
    imageSave: '../../../public/save-2.svg',
    imageDetails: '../../../public/details.svg',
  },
  {
    id: 202,
    image: "https://spaceflightnow.com/wp-content/uploads/2022/03/eva79-helmetcam.jpg",
    date: "April 20, 2025",
    title: "The International Space Station Dmitriev commented on the arrival",
    imageLike: '../../../public/like-2.svg',
    imageDislike: '../../../public/dislike-2.svg',
    imageSave: '../../../public/save-2.svg',
    imageDetails: '../../../public/details.svg',
  },
  {
    id: 203,
    image: "https://spaceflightnow.com/wp-content/uploads/2022/03/eva79-helmetcam.jpg",
    date: "April 20, 2025",
    title: "Meeting of Russian cosmonaut Oleg Platonov on the ISS",
    imageLike: '../../../public/like-2.svg',
    imageDislike: '../../../public/dislike-2.svg',
    imageSave: '../../../public/save-2.svg',
    imageDetails: '../../../public/details.svg',
  },
  {
    id: 204,
    image: "https://spaceflightnow.com/wp-content/uploads/2022/03/eva79-helmetcam.jpg",
    date: "April 20, 2025",
    title: "Crew Dragon ship with Russian Platonov docked to the ISS",
    imageLike: '../../../public/like-2.svg',
    imageDislike: '../../../public/dislike-2.svg',
    imageSave: '../../../public/save-2.svg',
    imageDetails: '../../../public/details.svg',
  },
  {
    id: 205,
    image: "https://spaceflightnow.com/wp-content/uploads/2022/03/eva79-helmetcam.jpg",
    date: "April 2, 2025",
    title: "Russia and the United States should cooperate to bring the ISS",
    imageLike: '../../../public/like-2.svg',
    imageDislike: '../../../public/dislike-2.svg',
    imageSave: '../../../public/save-2.svg',
    imageDetails: '../../../public/details.svg',
  },
  {
    id: 206,
    image: "https://spaceflightnow.com/wp-content/uploads/2022/03/eva79-helmetcam.jpg",
    date: "April 29, 2025",
    title: "The Crew Dragon ship with Platonov on board went to the ISS",
    imageLike: '../../../public/like-2.svg',
    imageDislike: '../../../public/dislike-2.svg',
    imageSave: '../../../public/save-2.svg',
    imageDetails: '../../../public/details.svg',
  },
]